version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: kelner-mysql
    networks:
      - kelner
    ports:
      - '3307:33060'
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: kelner-phpmyadmin
    restart: always
    ports:
      - '8080:80'
    networks:
      - kelner
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  api:
    image: dacharat/kelner-server
    restart: always
    ports:
      - '3000:3000'
    command: yarn dev
    depends_on:
      - db
    container_name: kelner-server
    networks:
      - kelner
    volumes:
      - .:/app
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: kelner-mysql
      NOTIFICATION_HOST: http://notification:2541

  schedule:
    image: dacharat/kelner-scheduling
    restart: always
    ports:
      - '7777:7777'
    command: yarn start
    networks:
      - kelner
    container_name: kelner-scheduling
    environment:
      SCHEDULE_CRON: 1 17 * * *
      HOST: http://api:3000

  notification:
    image: dacharat/kelner-notification
    restart: always
    ports:
      - '2541:2541'
    command: yarn start
    networks:
      - kelner
    container_name: kelner-notification

volumes:
  db_data:
networks:
  kelner:
